### ISSUE TITLE
ES6 in js files throws error in uglify

### ISSUE THREAD

**Issue by SheepFromHeaven** [biotope/biotope-build#117]
**Currently**:

One cannot use ES6 in js files as the uglify task will then throw an error. 

**Wish**:
As more and more ES6 features are supported by all browser, there should be a way to use js files without babel and uglify them.

**Comment by janrembold** [comment]
This should be easily possible by composing the `uglify-es` package into our uglify task. See https://github.com/terinjokes/gulp-uglify#using-a-different-uglifyjs

Any PRs are welcome! :) But please check backwards compatibility to ES5 and maybe also add some ES6 tests
