### ISSUE TITLE
remove eot and ttf iconfont generation

### ISSUE THREAD

**Issue by timomayer** [biotope/biotope-build#12]
remove eot and ttf iconfont generation woff and woff2 is enough fo all browsers we support.

**Comment by janrembold** [comment]
I did a test a few months ago for woff2 generation but rejected the plugin for now because it uses node-gyp to create woff2 files. We need to investigate for other options or maybe the woff2 plugin author changed his plugin by now?!

**Comment by timomayer** [comment]
you are right. but lets at least remove eot

**Comment by jurekbarth** [comment]
Is there still a need for an iconfont? There are plenty reasons to use SVG icons (https://css-tricks.com/icon-fonts-vs-svg/ http://www.responsiveicons.co.uk/ https://livicons.com/). Support is doable for IE9 and above.

**Comment by timomayer** [comment]
I agree but we need it for backward compatibility because existing projects are using iconfonts. With this ticket we can cleanup the iconfont task, there is another ticket for integrating Svgsprite support into biotope build
