### ISSUE TITLE
add style linters which make sure our component based apporach is followed

### ISSUE THREAD

**Issue by timomayer** [biotope/biotope-build#121]
https://github.com/postcss/postcss-bem-linter
https://github.com/stylelint/stylelint

**Comment by tiagomapmarques** [comment]
`stylelint` already has a bem-pattern linter (`stylelint-selector-bem-pattern` ([link](https://www.npmjs.com/package/stylelint-selector-bem-pattern))) that incorporates `postcss-bem-linter`.

Though the package is currently looking for maintainers.

**Comment by lhwparis** [comment]
thanks @tiagomapmarques . didnt know that repo thanks. but since it is looking for maintainers and i in general prefer to have not that much "wrapper-libraries" which are just wrapping other libs it is better to use stylelint and postcss-bem-linter separately what do you think?

**Comment by tiagomapmarques** [comment]
Usually if packages reach a "peak" state, then I'd use them regardless. IMO that's the case for these linter packages (by "peak" state I mean packages like `capitalize`[[link](https://www.npmjs.com/package/capitalize)] whose objective is clear and that will most likely not change over time - even if it's not been updated for 3 years).

From the `stylelint` official page, they mention the plugin as recommended [[link](https://stylelint.io/user-guide/plugins/)], so I'd say it's somewhat safe to bet on it.

**Comment by timomayer** [comment]
I agree in some parts but I think it is easier to maintain to write some lines of code by yourself to get both linters to work instead of using a wrapper library which maybe is unmaintained. We at least should look into how they are handling the dependency to the main bem Linter lib because of the version number is fixed and this repo is no longer maintained we get stuck with an older version of bem linter.

**Comment by jurekbarth** [comment]
I'll close here in favor of @biotope/biotope-quality-gate
