### ISSUE TITLE
Merging of scripts ignores comments

### ISSUE THREAD

**Issue by SheepFromHeaven** [biotope/biotope-build#126]
# Current:

Commenting a script tag in the head.scripts.hbs throws an error in the build process.

# Wish:

We should be able to ignore comments.

**Comment by janrembold** [comment]
@SheepFromHeaven I don't get the problem. What are you commenting exactly? An example would help.

Don't know if this is related, but we have a configurable uglify-comment-regex that might be involved: https://github.com/biotope/biotope-build/blob/master/config.js#L168

**Comment by SheepFromHeaven** [comment]
@janrembold this was a configuration problem. Thanks!
