### ISSUE TITLE
bioInclude helper can not send array to partial

### ISSUE THREAD

**Issue by smohadjer** [biotope/biotope-build#127]
Before switching from dot.js to handlebars.js we could send parameters of type array into a partial when including the partial in another template. This way we could iterate the array in partial to generate HTML we needed. It seems by switching to biotope we lost that functionality. Below is an example of what I need to migrate to biotope and use bioInclude helper instead of ftf.include:

`
{{= ftf.include("downloadSearch.fund.form.html", {placeholder: 'Lorem ipsum', funds: [{isin:"DE0000123456789",name:"BBBank Dynamik Union"},{isin:"DE0000987654321",name:"BBBank EuroRente 2017"},{isin:"DE0000111122222",name:"BBBank Konzept Union"}]  })  }}
`

Any idea how this could be done?

**Comment by smohadjer** [comment]
Could you revise the example I posted so I can understand what you mean?

**Comment by jurekbarth** [comment]
@smohadjer let me try to explain:

You have a folder structure similar to this one:
```
| src
  | components
    | accordion
      | scaffolding
         | demo.hbs
         | demo.json
      | accordion.hbs
```

`demo.hbs`
```
{{> 'components/accordion/accordion' data.components.accordion.scaffolding.demo}}

```
`demo.json`
```
["banana", "apple", "melon"]
```
`accordion.hbs`
```
<ul>
  {{#each this}}
    <li>{{this}}</li>
  {{/each}}
</ul>
```

Hope this helps 👍

**Comment by smohadjer** [comment]
So now we need three files instead of one just to send an array parameter to a component?! We used to do this without any additional files before moving to biotope simply using array parameters.

**Comment by janrembold** [comment]
Actually, you only need one additional file, the JSON file. This gets parsed into the globally available `data` object and is structured exactly as the folder/file structure inside `src` folder.
 
But yes, handlebars is not capable of handling Arrays or Objects by default. 
Closing this for now...

**Comment by smohadjer** [comment]
And how does this work with bioInclude?

**Comment by smohadjer** [comment]
And how do I pass additional parameters (of string type) to my component? I will really appreciate it if some biotope expert could translate the example I put in my question to biotope so I can understand how this magic works.

**Comment by jurekbarth** [comment]
@smohadjer what @janrembold mentioned or the what i described above? For Jan's approach you could use `with` which is a default helper by handlebars. `bioInclude` should pass down data like the build in handler. There's and `object` attribute which is handled differently, see here: https://github.com/biotope/biotope-build/blob/master/lib/hb2-helpers.js#L92
