### ISSUE TITLE
Es6 node_modules are not transpiled properly

### ISSUE THREAD

**Issue by dweiger** [biotope/biotope-build#129]
If I use a es6 plugin from node_modules and import it to my own plugin the code is not transpiled to es5. That leeds to problems with ie11. 
A solution would be to add 'node_modules' to gerneralIcludePaths in webpack.config.js.
I already did that in the branch 'fix-es6-node-modules'. It works for me.
@SheepFromHeaven or @jurekbarth do you see any problems with including the node modules here? 
If so we should find another solution.

**Comment by janrembold** [comment]
PR https://github.com/biotope/biotope-build/pull/130
