### ISSUE TITLE
How to test components?

### ISSUE THREAD

**Issue by jurekbarth** [biotope/biotope-build#137]
We don't have a standard test runner at the moment. Also we're lacking support for E2E-Tests. 

In BioElement we use Mocha and Chai? Here we use AVA? How to choose and what are the points/functionalities we should look for?

**Comment by janrembold** [comment]
@jurekbarth I have no preferences for or against a specific test runner. The example I found for testing Gulp pumps was written with Ava, but I'm pretty sure this is also possible with Mocha/Chai.

Important for those tests is primarily that those tasks do what they should do, for example SASS => Compile SASS to CSS, Autoprefixer => Add CSS prefixes and so on...

In the past we had some cases that updating depending modules (even hotfix releases) that had breaking changes and broke the whole process.

IMO main goal should be that updating any package in Biotope should be possible without manual testing of any facet of the build process.

**Comment by SheepFromHeaven** [comment]
Frozen for now. @tiagomapmarques please keep tests in mind for v7 😃
