### ISSUE TITLE
SASS Caching

### ISSUE THREAD

**Issue by jurekbarth** [biotope/biotope-build#145]
I have SASS caching problems. If i edit a partial the rebuild starts but the output doesn't reflect the changes. If i comment out the specific lines (https://github.com/biotope/biotope-build/blob/master/tasks/sass.js#L17) everything works as expected.

**Comment by alxbenz** [comment]
I refactored both sass tasks into one. https://github.com/biotope/biotope-build/tree/refactor_sass
Can you please test if this fixes your problem? It looked good on my side.
Some additional testing would be apreciated.

**Comment by jurekbarth** [comment]
@alxbenz will do so right now 👍

**Comment by jurekbarth** [comment]
Hi @alxbenz i've changed the path for resources/scss to be compatible with unix systems, otherwise it works 👍
