### ISSUE TITLE
Add possibility to import SVGs

### ISSUE THREAD

**Issue by SheepFromHeaven** [biotope/biotope-build#149]
In the new template strings I would like to have the possibility to import SVG icons so they get rendered in the html. Please add this possibility

**Comment by jurekbarth** [comment]
You can have a look at here:
https://github.com/biotope/biotope-build/tree/webpack-svg-loader
and here for implementation details:
https://github.com/biotope/experimental-biotope-components/tree/wip-inline-svg

Still i'm having problems using bio element to not escape my SVG stuff. Maybe we could switch to a "normal" Web Component here without any sugar to make it easier to deal with SVG's. What do you think?

**Comment by timomayer** [comment]
what do you mean by normal web component?

**Comment by jurekbarth** [comment]
We are using BioElement on top of hyperHTML Element which extends HTMLElement. We could use a normal webcomponent like so

```
import mySvg from './mySvg'

class Icon extends HTMLElement {
  constructor() {
    super();
    this.innerHTML = mySVG;
  }
}
```

This way my svg is not sanitized. Tradeoffs are ok for me, because the icon won't have child nodes.

**Comment by timomayer** [comment]
thanks for the explanation. i agree it is ok since svg has no child nodes.
Whats the reason behind? Is it an hyperHTML bug?

**Comment by jurekbarth** [comment]
Not a bug a feature. It sanitizes input by default. That's a good thing 99% of the time, but there's no way around it, at least none i'm aware of. Would be handy to have something like react's dangerouslySetInnerHTML method.

**Comment by timomayer** [comment]
can you open a ticket in hyperHTML repo with this exact usecase. for the time there is no other solution we should add the workaround for svgs to our documentation.

**Comment by jurekbarth** [comment]
@timomayer will do so 👍

**Comment by SheepFromHeaven** [comment]
@jurekbarth are you still working on that? 🙏 also have a look at #157

**Comment by jurekbarth** [comment]
@SheepFromHeaven yes :) it's basically done i would like to publish that stuff we merge https://github.com/biotope/biotope-build/pull/159

**Comment by jurekbarth** [comment]
#178
