### ISSUE TITLE
CSS files not minifying and charset

### ISSUE THREAD

**Issue by alxbenz** [biotope/biotope-build#151]
There is a problem with css minification.
Currently the css files will not get minified when using the build. 
Additionaly the @charset will be removed.
This may lead to icons not working correctly.

I tested two versions: 
5.3.1 - working as intended
5.4.2 - causing the behaviour described above

**Comment by jurekbarth** [comment]
@alxbenz is `@charset` really a thing in 2018? Shouldn't that be a html header anyway?

Sorry for the german, couldn't find the same in english:
Beachten Sie: Da der HTTP-Header höhere Priorität als eine @charset-Angabe innerhalb des Dokuments hat, sollten Sie immer beachten, ob die Zeichencodierung bereits im HTTP-Header angegeben ist. Wenn das der Fall ist, muss @charset auf dieselbe Zeichen­codierungs­angabe gesetzt werden. Sie hat nur dann einen Effekt, wenn das Stylesheet in einem Kontext gelesen wird, wo es keinen HTTP-Header gibt (z.B. von der lokalen Festplatte).
https://www.w3.org/International/questions/qa-css-charset.de#atcharset

**Comment by timomayer** [comment]
@jurekbarth some of our clients have weird legacy server configuration we cannot change. so yes it is a thing :/

**Comment by jurekbarth** [comment]
@alxbenz #152 should fix the issue 👍 Maybe also test this one or merge it into your branch.

**Comment by alxbenz** [comment]
Tested this in one of my projects and it is looking good.

**Comment by jurekbarth** [comment]
@alxbenz can you also review the pr?
