### ISSUE TITLE
Add an loader to be able to include inline SVG files inside SASS files.

### ISSUE THREAD

**Issue by VI-Lukas** [biotope/biotope-build#157]
Tried to put an inline svg icon on a pseudo element

&:after {
				display: block;
				background-image: url(../../relativeUrl);
				height: 8px;
				width: 5px;
				background-color: red;
}

ERROR in ./src/resources/img/icon.svg 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.

**Comment by jurekbarth** [comment]
Loader needs to be included, i'll work on that issue

**Comment by VI-Lukas** [comment]
I was able to include the SVG trough the background-image property with ab absolute path.

**Comment by jurekbarth** [comment]
#178
