### ISSUE TITLE
RFC: Move back to ts-loader for typescript files

### ISSUE THREAD

**Issue by jurekbarth** [biotope/biotope-build#162]
I would like to switch back to ts-loader for typescript-compilation. In my first initial test ts-loader was faster in startup and ongoing builds, further on i was not able to produce d.ts files with awesome-typescript-loader. As @marwesfur described in #161 it would be a really nice to have feature.

Is there anything i need to consider or is it **just** a switch back?

**Comment by jurekbarth** [comment]
@SheepFromHeaven i'll submit a pr soonish 👍

**Comment by timomayer** [comment]
https://github.com/biotope/biotope-build/pull/178
