### ISSUE TITLE
Cleanup branches

### ISSUE THREAD

**Issue by SheepFromHeaven** [biotope/biotope-build#165]
Delete stale branches

**Comment by tiagomapmarques** [comment]
@timomayer, can we fork the repo to keep these stale branches and delete them from the main repo?

**Comment by timomayer** [comment]
i already started cleanup and we do not need most of the stale branches so i think no need for the fork

**Comment by timomayer** [comment]
95% of the cleanup is done. only the styleguide branches, vNext and one legacy branch for a 4.4.1 fix version are open. the last one can not be closed for now because of a project dependency we can not yet change. so i would like to close this ticket. do you agree?

**Comment by jurekbarth** [comment]
@timomayer can we publish this branch on npm?

**Comment by timomayer** [comment]
We can but not sure why it should be necessary. for the 2 proects which are still using it we can not change the package.json at the moment, not even just from github to npm so we need the branch anyway

**Comment by timomayer** [comment]
Add Legacy info to readme of this branch
