### ISSUE TITLE
Create migration guide 5.3 => 5.x

### ISSUE THREAD

**Issue by SheepFromHeaven** [biotope/biotope-build#166]
Update and move migration guide here

**Comment by timomayer** [comment]
@jurekbarth this is still open and i think important. now it is more a migration guide from
5.3 => 6.1 we need

**Comment by jurekbarth** [comment]
@timomayer i think we're pretty up to date: https://github.com/biotope/biotope-boilerplate/blob/master/MIGRATION.md
If not please reopen again 👍
