### ISSUE TITLE
New file recognition

### ISSUE THREAD

**Issue by SheepFromHeaven** [biotope/biotope-build#167]

**Comment by timomayer** [comment]
öhm we are already using gulp watch for exactly that :)

**Comment by SheepFromHeaven** [comment]
Idea: gulp-watch gets the changed files passed to the callback. Use this as an indicator what to rebuild.

**Comment by SheepFromHeaven** [comment]
Question: How can we pass parameters to a gulp task?

**Comment by hummelch** [comment]
+ 1
It causes issues in big projects!

**Comment by jurekbarth** [comment]
I think it's just a matter of performance and is not really fixable at the moment, let's keep an eye on that issue with the next version of biotope/build. Feel free to reopen in necessary.
