### ISSUE TITLE
Changelog outdated

### ISSUE THREAD

**Issue by timomayer** [biotope/biotope-build#197]
We should add versions >5.5 to the changelog and also make sure in future PR that updating the changelog is part of every PR which adds a new feature

**Comment by timomayer** [comment]
https://github.com/biotope/biotope-build/pull/304

**Comment by SheepFromHeaven** [comment]
@timomayer IDK if you know, but there are keywords like "Resolved by" or "Fixed by" that autoclose issues on merge. :)

**Comment by SheepFromHeaven** [comment]
https://help.github.com/en/articles/closing-issues-using-keywords

**Comment by timomayer** [comment]
i know but will not close until final release of 7.0.0 cause changelog may change due to the fixes i am doing.

**Comment by timomayer** [comment]
fixed with 7.0 release
