### ISSUE TITLE
Issue with resources/components vs. components folder in dist

### ISSUE THREAD

**Issue by timomayer** [biotope/biotope-build#200]
The new copy task copies every file inside a component folder to /components/* in dist. Former versions of biotope copied the components to /resources/components/* in dist folder.

Since some projects can not changed in the way that ONLY the resources folder is deployed to live systems this makes files in the /components/ folder unacessable.

Suggestion:
copy whole /components/* folder to /resources/components so it is available twice for backward compat reasons. This should be done before releasing the version with the new copy task.

**Comment by timomayer** [comment]
@jurekbarth any thoughts on that?

**Comment by jurekbarth** [comment]
@timomayer why should we put components it the root? I would keep that for version 7 and for now stick to resources/components In the latest beta release it should be all fixed :)

**Comment by timomayer** [comment]
That's OK for me, thanks!
