### ISSUE TITLE
integrate a swagger api server

### ISSUE THREAD

**Issue by timomayer** [biotope/biotope-build#22]
eg: https://github.com/gersongoulart/gulp-swagger
1. evaluate if there is a better plugin for that
2. integrate it to build framework so we have only swagger json files in _mock folder and they auto generate /api/* endpoints

**Comment by smohadjer** [comment]
Sorry for sounding stupid, but what problem are we trying to solve with this?

**Comment by timomayer** [comment]
hey @smohadjer thanks for the question not a stupid one since the link i am posted was not the correct one it is https://github.com/subeeshcbabu/swagmock so we can create mock files directly out of a swagger api specification file and can use that in our biotope frontends

**Comment by smohadjer** [comment]
My question was on a higher level, but from this link I can see that this allows us to generate json dynamically rather than using static json files, right?

**Comment by timomayer** [comment]
mocks are not only used as mock files in our projects in many cases we are defining the API by writing this mock files. for that case it is not enough to just have an undocumented mock file, you need an API schema for the backend. a swagger mock definition is the defacto standard for that and we can generate our mock data out of that and a little bit more "dynamic" compared to our static mock files.

**Comment by janrembold** [comment]
@timomayer This tool is a swagger mock server that we can use to simulate API calls, right? 
For development that would be really cool but how does that fit into our static distribution folder? Our static preview build does not allow any running tasks or server functionality.

**Comment by timomayer** [comment]
It can generate static mock json files too (we can use that option for build)

**Comment by timomayer** [comment]
i have checked this one as well: https://github.com/typicode/json-server
this one can generate the static json, not sure about swaggermock and this functionality.

**Comment by timomayer** [comment]
a very interesting looking one:
https://github.com/json-schema-faker/json-schema-faker

**Comment by timomayer** [comment]
and one more, exactly what we need :)
https://github.com/coryhouse/mock-api-example/

https://medium.freecodecamp.org/rapid-development-via-mock-apis-e559087be066

**Comment by timomayer** [comment]
we should extract that to another biotope project (not build framework), biotope-json-mock-generator

scope:
define a json-schema (swagger schema)
validate json schema (lint)
generate "pseudo-dynamic" mock files for serve mode
generate static mock files for build mode

**Comment by SheepFromHeaven** [comment]
@timomayer I created a repository https://github.com/biotope/biotope-json-mocker
So I will close this now :ok_hand:
