### ISSUE TITLE
TravisCI automated testing 

### ISSUE THREAD

**Issue by janrembold** [biotope/biotope-build#23]
I'm thinking about testing all build framework tasks but would like to discuss different approaches of doing that in a useful and sustainable way.

Our framework (<5.x) had Travis tests for 2 different goals:

1. Complete build task executing successful  
2. Compare created demo files (styles.all.min.css, scripts.all.min.js,...) with fixtures

Problems we discovered with test nr. 1 were very unspecific error messages (Build is broken).
Test nr. 2 was very fragile because any minor change within plugins or demo code structure changed the output and broke the tests.

**I would like to discuss 2 different topics here:**

1. What kind of tests should we write for the build framework?
2. What fixture data / demo content can we use?

**Comment by janrembold** [comment]
Question 1) I would like to test each and every task by itself. This would include something like

- copy content from some demo content repo
- run task
- compare output with fixtures

The comparison should be done in a logical way. In the past we had lots of trouble with bit-by-bit comparison because of compilation differences between Windows and Mac. 

Question 2) This is a little bit tricky. We need demo content for different places:
- Demo Repository (currently the demo-5.x branch)
- Testing fixtures
- Documentation

I see multiple problems with that because the demo repo and documentation code should be tightly coupled. Both should be placed somewhere around the frontend-framework. Testing (and the resulting fixtures) should be related to the build framework. I don't like the idea of keeping demo content up2date in 3 or more different places

**Comment by alxbenz** [comment]
1) I agree with you on testing every task by itself, like unit tests for gulp-tasks. 
2) I think every tasks should get its own demo content. Maybe this doesn't need to be a full repo, but rather small snippets, that are included in the build-framework.

An interesting reading resource I found is: https://snugug.com/musings/unit-testing-gulp-tasks/

Another topic to discuss is the testing framework which we should use for these tests and general unit testing future components.

**Comment by janrembold** [comment]
Interesting article about the lazypipe plugin. We already started to extract methods into the /lib modules. This might be the next step to divide gulp tasks from business logic.

As another side-effect of this modular approach we should integrate some lazy loading of node modules. This is still a big pain, especially on Windows. I think about moving most require calls into the modules or use some kind of node lazy loading plugins.

**Comment by janrembold** [comment]
I did a major p-o-c refactoring that ended up with a complete lazy loading for each task and two examples of lazypipes (sass and cleanCss). Those lazy pipes are tested in an exemplary Ava test that is already successfully tested within Travis CI. See https://github.com/frontend-framework/build-framework/tree/lazy-load-plugins 

I also added a pre-release tag "5.2.0-rc1" to this current branch state. You can test this branch for each >= 5.1.x frontend framework.

Next step would be to refine the modules to allow injecting of custom configurations and move all relevant pipes to lazypipe.

**Comment by janrembold** [comment]
Testing is initially added to current PR https://github.com/biotope/biotope-build/pull/68
