### ISSUE TITLE
Error Message is inaccurate

### ISSUE THREAD

**Issue by bennyvi** [biotope/biotope-build#24]
If I include a component in layouts that does not exist, the following error message will appear:
partial not found: block helper fallback will be used and
context.fn is not a function in "C:\xxx\xxx\xxx\frontend-framework-master\src\pages\xxx.hbs"

Probably this part must be adjusted in hbs-helpers.js

`// if partial doesn't exist use block failover
		if (!partial) {
			console.log(colors.red('partial not found: block helper fallback will be used'));
			return context.fn(this);
		}`

**Comment by alxbenz** [comment]
The Error Message should include the partial name that can not be found. 
The error "context.fn is not a function..." should not appear. Instead there should be a check, if the include helper is used as a block or not.

**Comment by janrembold** [comment]
Error messages are an overall framework topic. I would like to do a complete roundup on error messages on each task. 

Currently we have a wild mix of error messages:
1. internal plugin logging
2. error event listeners with console log or special reporters 
3. error event listeners with notify plugin

I would really like to see gulp-notify (https://github.com/mikaelbr/gulp-notify) in all development-relevant tasks like lint errors/warnings, hbs or sass errors. This helps in daily business to develop faster and see errors earlier.

Other informational logs (uglified/minified info...) should remain in console only.

Do Windows users use there "toaster" notifications? For me, as a Mac user, I can say that I really appreciate my control center messages.

**Comment by timomayer** [comment]
@janrembold can ypu please extract your last commit to a new ticket since i want to close this one. it is resolved with 5.2.1
