### ISSUE TITLE
Rethink debug option

### ISSUE THREAD

**Issue by janrembold** [biotope/biotope-build#26]
Currently the global debug flag "config.global.debug" creates huge amounts of console logs. This is no helpful information anymore. 

I would like keep debugging information but on a more fine granular level. Maybe we should add flags like the "config.global.tasks" property for debug outputs. 

Proposal would be: 
`config.global.debug: {
  cleanCss: false,
  useref: true,
  ....
}`

What do you think? @alxbenz @timomayer

**Comment by timomayer** [comment]
like that @janrembold. but we should look into cleaner error/debug output anyways

**Comment by jurekbarth** [comment]
@timomayer @janrembold is it about really debugging or more about the console output?
