### ISSUE TITLE
update to gulp4

### ISSUE THREAD

**Issue by timomayer** [biotope/biotope-build#28]
Gulp4 is final!
https://www.joezimjs.com/javascript/complete-guide-upgrading-gulp-4/

**Comment by timomayer** [comment]
- check if all our dependencies are gulp4 ready
- do migration to gulp4

**Comment by timomayer** [comment]
https://github.com/gulpjs/gulp/issues/861

**Comment by janrembold** [comment]
@timo
Are there any pain points, except gulp-util usage, with gulp@3.9.1?

We just figured out that this would be a major rebuild of the whole task structure.

**Comment by timomayer** [comment]
Not at the moment. Dont know if gulp3 will be supported in the future and will cause problems then?

**Comment by SheepFromHeaven** [comment]
Closed for now. Reopen if needed.
