### ISSUE TITLE
_assets folder is missing in dist folder after gulp build is done (6.2.0)

### ISSUE THREAD

**Issue by smohadjer** [biotope/biotope-build#288]

**Comment by jurekbarth** [comment]
@smohadjer sure, that's because it starts with an underscore. Renaming the folder to `assets` would solve the problem.

**Comment by smohadjer** [comment]
Why should starting a folder's name with an underscore cause a problem in the first place?

**Comment by timomayer** [comment]
@jurekbarth  please add the old variant with _ too because everything else would be a breaking change and this is not easy to do in most projects.
