### ISSUE TITLE
handlebars.helpers.js module is not loaded on build

### ISSUE THREAD

**Issue by tiagoaguiar31** [biotope/biotope-build#291]
On the build process, the module **handlebars.helper.js** is not found and isn't loaded. The path has already been corrected on PR #290 , but an empty object is returned.
Since the @biotope/biotope-boilerplate requests the @biotope/biotope-build as a dependency to build the project and thereafter the @biotope/biotope-build request the file **handlebar.helpers.js** as a module in order to build on the project, it causes a circular dependency (returning an empty object to prevent an infinite loop).

**Comment by timomayer** [comment]
https://github.com/biotope/biotope-build/commit/caf1d6b09acb4f21f5dc153ff0dc294c2b02a9b5
