### ISSUE TITLE
Handlebars static and dynamic partials naming

### ISSUE THREAD

**Issue by alxbenz** [biotope/biotope-build#3]
The handlebars runtime partials have a different naming convention, than partials in the hb:static task.

The runtime partials should be updated to have the same name as the static partials to make them usable by both tasks interchangeable.

- static partials always use the full path name `components/demo/partial`
- dynamic partials use only the filename `partial`

**Comment by jurekbarth** [comment]
@janrembold, @alxbenz  as we're moving towards web components, i'll close for now.
