### ISSUE TITLE
Add Node Security task

### ISSUE THREAD

**Issue by janrembold** [biotope/biotope-build#30]
We should implement https://github.com/nodesecurity/gulp-nsp to check our node modules.

**Comment by timomayer** [comment]
@janrembold i thought about this task and i prefer to not have it included into the build framework. i think build framework should concentrate on build tasks. this can either be an additional biotope project (biotope-security) or we decide to use external services for that like snyk. what do you think?

**Comment by janrembold** [comment]
@timomayer After my evaluation of nsp I would like to test snyk as well. nsp is not suitable for our purposes. But anyhow, it is really easy to integrate nsp/snyk into our Travis CI configuration without including it into the framework directly.
