### ISSUE TITLE
Typescript : JavaScript heap out of memory

### ISSUE THREAD

**Issue by VI-Lukas** [biotope/biotope-build#48]
Start with gulp serve.

After view times webpack:ts runs it takes longer and longer and at some point running into:

Starting 'webpack:ts'...
<--- Last few GCs --->

[13936:0000020A1C0B82A0] 2906109 ms: Mark-sweep 1410.9 (1461.0) -> 1410.9 (1461.0) MB, 1618.4 / 0.0 ms last resort GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 000003CDEB725EE1 
2: /* anonymous /(aka / anonymous */) [C:\<projectPath>\node_modules\typescript\lib\typescript.js:20797] [bytecode=0000012474DB12A9 offset=3](this=000001CA07782311 ,ElementKind=
0000012985E5CA71 )
4: bindObjectLiteralExpression(aka bindObjectLiteralExpression) [C:\Users...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
1: node_module_register
2: v8::internal::FatalProcessOutOfMemory
3: v8::internal::FatalProcessOutOfMemory
4: v8::internal::Factory::NewTransitionArray
5: v8::internal::EhFrameIterator::DecodeSLeb128
6: v8::internal::JSReceiver::GetOwnPropertyDescriptor
7: v8::internal::JSReceiver::GetOwnPropertyDescriptor
8: v8::internal::JSReceiver::GetOwnPropertyDescriptor
9: v8::internal::JSReceiver::class_name
10: v8::internal::JSReceiver::GetOwnPropertyDescriptor
11: v8::internal::LookupIterator::PrepareTransitionToDataProperty
12: std::vector<v8::internal::compiler::MoveOperands * __ptr64,v8::internal::ZoneAllocator<v8::internal::compiler::MoveOperands * __ptr64> >::_Reallocate
13: std::vector<v8::internal::compiler::MoveOperands * __ptr64,v8::internal::ZoneAllocator<v8::internal::compiler::MoveOperands * __ptr64> >::_Reallocate
14: std::vector<v8::internal::compiler::MoveOperands * __ptr64,v8::internal::ZoneAllocator<v8::internal::compiler::MoveOperands * __ptr64> >::_Reallocate
15: std::vector<v8::internal::compiler::MoveOperands * __ptr64,v8::internal::ZoneAllocator<v8::internal::compiler::MoveOperands * __ptr64> >::_Reallocate
16: 0000014AEA2847A1

**Comment by janrembold** [comment]
This is not a fix but it helps to reduce reloading the build framework. Add parameter `--max_old_space_size=4096` (or even higher memory value if you have enough RAM) to your "scripts"->"start" property, see https://github.com/biotope/biotope/blob/master/package.json#L18

Other possibility would be to use pump as proposed here https://github.com/biotope/biotope-build/issues/59
Maybe this helps to better clean up memory consumed by `webpack-stream` (or `webpack` itself). But this is just a guess...

**Comment by janrembold** [comment]
I removed manual error listener and added plumber as global error listener in webpack-stream task. Maybe this helps to better exit the task and do correct memory de-allocation. Please test: https://github.com/biotope/biotope-build/pull/68 or use https://github.com/biotope/biotope-build.git#uglify-pump-test as @biotope/build target path in package.json (this is only for projects > 5.2.x)

**Comment by janrembold** [comment]
@SheepFromHeaven No worries. Adding another line to tsconfig.json fixes this error. Should be handled by includes/excludes but isn't. My webpack task is now running between 700ms up to 1,4s without any memory issues!!!!! But no party before Windows is checked...

```
"awesomeTypescriptLoaderOptions": {
		"useCache": true,
		"reportFiles": [
			"src/**/*.{ts,tsx}"
		]
},
```

**Comment by SheepFromHeaven** [comment]
@janrembold checked it too. Redux errors went away after upgrading the version.
Runs perfectly smooth and no memory leaks until now!

Love this solution. Fast and steady.

**Comment by janrembold** [comment]
Fixed with https://github.com/biotope/biotope-build/pull/97
