### ISSUE TITLE
Add automated tests for each gulp task

### ISSUE THREAD

**Issue by alxbenz** [biotope/biotope-build#5]
We need automated Travis CI tests for each gulp task.

I think about testing each task by its own, not only a full gulp build like it is done in Frontend Framework repository right now.

Testing approaches need to be discussed...

**Comment by janrembold** [comment]
https://github.com/frontend-framework/build-framework/tree/lazy-load-plugins

**Comment by janrembold** [comment]
https://github.com/biotope/biotope-build/pull/68
