### ISSUE TITLE
Gemini: Visual regression testing

### ISSUE THREAD

**Issue by timomayer** [biotope/biotope-build#50]
Check Gemini. Looks like an interesting alternative for our visual regression tests
https://github.com/gemini-testing/gemini
to integrate with gulp: https://github.com/gemini-testing/gemini/blob/master/doc/programmatic-api.md
to use it with jenkins local builds: https://github.com/Saulis/gemini-browserstack
maybe use: https://github.com/gemini-testing/gemini-gui or https://github.com/gemini-testing/html-reporter for test results

**Comment by jurekbarth** [comment]
@timomayer can we close? We'll make a package for that as soon as we make progress here.

**Comment by SheepFromHeaven** [comment]
Closed for now. Reopen if needed.
