### ISSUE TITLE
Build task not finishing if uglify task= false

### ISSUE THREAD

**Issue by luiswill** [biotope/biotope-build#60]
When trying to debug and setting uglify task to false the build task doesn't finish his job until the end.
So the `dist` folder is incomplete.

###  **How to reproduce error :** 
Setting uglify task to false in `projectConfig.js`

Last tasks running : 
```
[
        'uglify:resources:dist',
	'uglify:components:dist',
	'cleanCss:resources:dist',
	'cleanCss:components:dist'
],
```
Last command line in terminal
`Finished 'cleanCss:resources:dist' after 2.6 s
`

### Possible solution :
uglify is not returning a callback.

@alxbenz is aware of that issue.

**Comment by janrembold** [comment]
Oh, thats not fully correct. The uglify task returns the callback, but in the wrong place :(

Normally pump executes the callback, when set as last parameter, after it is finished. But here we have multiple source and target folders that are uglified. 

The solution is to set and collect promises in each pump execution and call cb() after all of them returned.

`pump([ ...tasks...], somePromiseCreatorFunc)` => `Promise.all(collectedPromises).then(cb)`

**Comment by janrembold** [comment]
By the way, it would be cool to build a generic module that creates and collects those promises. We might need this function more often in the future if we're going to refactor more tasks to pump syntax.

**Comment by luiswill** [comment]
So with @janrembold we solved that issue.

We had to call the callback function even if uglify task is set to false.
I will pull request the change

**Comment by timomayer** [comment]
thanks @luiswill looking forward to the PR :)

**Comment by luiswill** [comment]
Done with PR #62 :)
