### ISSUE TITLE
uglify:false prevents components js from copying

### ISSUE THREAD

**Issue by markuspl** [biotope/biotope-build#73]
If you set uglify to false, js files located in the components/.../[js|ts] will not be copied to the dist folder.

Problem is, that the uglify task itself is copying the uglifiyed files to the dist folder.
To solve this, we need start an additional task, if the condition is false!

I'll already fixed it and will create a pr

**Comment by janrembold** [comment]
I think there might be another problem as well. In this case all files from uglify ignore list are also not copied to dist folder. 

Wouldn't it be better to copy all files to dist in first run, then select all *.js files there and ignore those from uglify ignore list. The resulting files should be uglified and sourcemapped.

**Comment by markuspl** [comment]
@janrembold Yeah, I guess so. I just tried it and all the files only referenced by the resource loader e.g. would not be copied.

As you mentioned we can change the gulp tasks like that:
1. copy js/ts files to tmp,
2. run webpack for ts
3. copy all to dist
4. run uglify (if enabled) except the ignored ones?

**Comment by janrembold** [comment]
The webpack task is responsible for bundling and copying the TS files. I would propose the following sequences:

In `build:dev` sequence:
1. Webpack copies TS files to /.tmp (this already works)
2. JS files can stay to keep development sequence as slim as possible

In `build` sequence:
1. Copy all JS files (already bundled TS files) from /.tmp to /dist
2. Copy all JS files from /src to /dist
3. Run uglify (if enabled) except ignored files

**Comment by markuspl** [comment]
@janrembold looks good for me, i'll try it tomorrow

**Comment by janrembold** [comment]
The copy sequences seem to be a little bit out of control. I think it would be good to have a close look into that and clean it up during refactoring. Especially this sequence seems to be useless:

1. Copy files from /src to /.tmp
2. Copy files from /.tmp to /dist

See: https://github.com/biotope/biotope-build/blob/master/index.js
```
		[
			'copy:dev:js'
		],
		[
			'copy:dist:js',
```

I also think there will be unused tasks left, like `copy:dist:ts`

**Comment by janrembold** [comment]
@markuspl Is there anything going on here?

**Comment by timomayer** [comment]
@markuspl any news here?

**Comment by janrembold** [comment]
Fixed with https://github.com/biotope/biotope-build/pull/105
