### ISSUE TITLE
Handlebars performance tweak proposal

### ISSUE THREAD

**Issue by janrembold** [biotope/biotope-build#77]
Problem is: We never know which template/page is currently visible in the browser or better on which page is the developer working on. 

In large projects it is still painful slow to statically re-render all templates (even though the new hb2 task has a 40-50% performance boost). 

I would propose to add the possibility to overwrite the template glob pattern (https://github.com/biotope/biotope-build/blob/master/tasks/hb2.js#L13) inside local projectConfig.js.

If a developer has a large task and needs to see only a single page it would reduce the static rendering time to (n-1/n) where n = number of page templates. This means it would reduce the duration from seconds to milliseconds.

**Comment by janrembold** [comment]
https://github.com/biotope/biotope-build/pull/71

**Comment by timomayer** [comment]
like the idea! but we have to make sure this only works for serve, not build

**Comment by timomayer** [comment]
@markuspl are you working on that task?

**Comment by jurekbarth** [comment]
@biotope/core-enforcer in my opinion we could close here, as we will not continue with hbs files. What do you think?
