### ISSUE TITLE
Iconfont folder is needed for build

### ISSUE THREAD

**Issue by SheepFromHeaven** [biotope/biotope-build#79]
Current:
If your project does not need a custom iconfont, you cannot remove the iconfont folders, as the build process will throw an error.

Wish:
The build process should be more tolerant and just ignore a non existing icon font folder.

**Comment by janrembold** [comment]
@SheepFromHeaven What kind of error do you see? I just removed the folder and didn't see any errors

**Comment by jurekbarth** [comment]
@janrembold  It's crashing the whole build process. 
The error: `Error: Error in template: ENOENT: no such file or directory, open 'src/resources/scss/fonts/iconfont/_icons.scss'`

**Comment by jurekbarth** [comment]
It's fixed in this PR #93
