### ISSUE TITLE
Component js/css resource build path

### ISSUE THREAD

**Issue by SheepFromHeaven** [biotope/biotope-build#84]
Current:
js/css resources located in the components folder are built to the destination *resources/components/*
This leads to different paths for images/json assets and js/css assets in the dev environment.

Wish:
The js/css resources as well as the rest of resources, should be built to just *components/* as they have a different meaning than resources.

**Comment by janrembold** [comment]
@SheepFromHeaven I'm totally with you for this change!
This would also be a nice breaking change to add the Entry Point proposal: https://github.com/biotope/biotope-build/issues/80

**Comment by janrembold** [comment]
@timomayer That's a good point. The way I changed the components copy task in https://github.com/biotope/biotope-build/pull/105 should make it much easier to handle the target folder by configuration

**Comment by SheepFromHeaven** [comment]
Closed for now. @tiagomapmarques please keep in mind for v7 🙏
